### ISSUE TITLE
TypeError: node.compareDocumentPosition is not a function

### ISSUE THREAD

**Issue by mrfratello** [Olical/react-faux-dom#146]
The method `selection.order` is updated in the D3.js library: https://github.com/d3/d3-selection/commit/146af5da2ed1bba5246e1e6a4d930f8c3d0adc5c#diff-e5d25ffcccb4560adf79cf542e9b0709L6

The essence of this update is that for comparing the elements positions used  method of DOM Element`compareDocumentPosition` (instead property `nextSibling`).

As far as I understand, the `react-faux-dom` for DOM manipulation used a Virtual Element. And that Virtual Element does not have the `compareDocumentPosition` method.

**Comment by Olical** [comment]
`compareDocumentPosition` isn't implemented, it could probably be added though, it just requires implementing a function that can hunt through the faux DOM and return the correct constant value. The constants would probably have to be defined on all nodes too. Behaviour should adhere to https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition

I won't get around this for a pretty long time since I'm only really fixing existing bugs at this point. I'm not really developing this project further. If someone wants to have a go at adding it I'd be more than happy to review a pull request.

**Comment by hamfatfat** [comment]
yarn build with react-script 2.1.8
Failed to compile.
Failed to minify the code from this file:
        ./node_modules/react-faux-dom/lib/_element.js:266

**Comment by Olical** [comment]
Sorry, this is a completely unrelated issue, would you be able to open another issue with some more context? I also have no idea what `react-script` is I'm afraid. I won't be able to fix whatever the issue is with so little information.
