### ISSUE TITLE
Broken D3 test

### ISSUE THREAD

**Issue by tibotiber** [Olical/react-faux-dom#93]
Just opening an issue for the broken test mentioned in #91.
```
✓ removi......
  ok 13 should be equal/home/travis/build/Olical/react-faux-dom/node_modules/d3-selection/build/d3-selection.js:635
  return node.style.getPropertyValue(name)
                    ^
TypeError: node.style.getPropertyValue is not a function
    at styleValue (/home/travis/build/Olical/react-faux-dom/node_modules/d3-selection/build/d3-selection.js:635:21)
    at Selection.selection_style [as style] (/home/travis/build/Olical/react-faux-dom/node_modules/d3-selection/build/d3-selection.js:631:9)
    at Test.<anonymous> (/home/travis/build/Olical/react-faux-dom/test/d3.js:87:14)
    at Test.bound [as _cb] (/home/travis/build/Olical/react-faux-dom/node_modules/tape/lib/test.js:66:32)
    at Test.run (/home/travis/build/Olical/react-faux-dom/node_modules/tape/lib/test.js:85:10)
    at Test.bound [as run] (/home/travis/build/Olical/react-faux-dom/node_modules/tape/lib/test.js:66:32)
    at Immediate.next (/home/travis/build/Olical/react-faux-dom/node_modules/tape/lib/results.js:71:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
...14 no plan found
⨯ fail  1
```

@Olical suggested:

> If I had to guess, it's some new property D3 tries to use, it may just need to be implemented. I'll take a look this week 😃
